export const consignmentOptions = [
    // { label: 'Office supplies', value: '53102400' },
    // { label: 'Computers', value: '43211500' },
    // { label: 'Computer accessories', value: '43211700' },
    // { label: 'Clothing', value: '53100000' },
    { label: 'Consumer electronics', value: '52161500' },
];

export const packageOptions = [
    { label: 'Bidón (tambor) de plástico de tapa no desmontable', value: '1H1' },
    { label: 'Bidón (tambor) de plástico de tapa desmontable', value: '1H2' },
    { label: 'Caja de aluminio', value: '4B' },
    { label: 'Caja de madera natural ordinaria', value: '4C1' },
    { label: 'Caja de madera natural de paredes a prueba de polvos (estancas a los pulverulentos)', value: '4C2' },
    { label: 'Caja de madera contrachapada', value: '4D' },
    { label: 'Caja de madera reconstituida', value: '4F' },
    { label: 'Caja de cartón', value: '4G' },
    { label: 'Caja de plástico expandido', value: '4H1' },
    { label: 'Caja de plástico rígido', value: '4H2' },
    { label: 'Saco (bolsa) de película de plástico', value: '5H4' },
    { label: 'Saco (bolsa) de tela resistente al agua', value: '5L3' },
    { label: 'Saco (bolsa) de papel de varias hojas', value: '5M1' },
    { label: 'Saco (bolsa) de papel de varias hojas, resistente al agua', value: '5M2' },
    { label: 'Envase y embalaje compuesto de recipiente de plástico, con un bidón (tambor) de acero', value: '6HA1' },
    { label: 'Envase y embalaje compuesto de recipiente de plástico, con una jaula o caja de acero', value: '6HA2' },
    { label: 'Envase y embalaje compuesto de recipiente de plástico, con un bidón (tambor) exterior de aluminio', value: '6HB1' },
    { label: 'Envase y embalaje compuesto de recipiente de plástico, con una jaula o caja de aluminio', value: '6HB2' },
    { label: 'Envase y embalaje compuesto de recipiente de plástico, con una caja de madera', value: '6HC' },
    { label: 'Envase y embalaje compuesto de recipiente de plástico, con un bidón (tambor) de madera contrachapada', value: '6HD1' },
    { label: 'Envase y embalaje compuesto de recipiente de plástico, con una caja de madera contrachapada', value: '6HD2' },
    { label: 'Envase y embalaje compuesto de recipiente de plástico, con un bidón (tambor) de cartón', value: '6HG1' },
    { label: 'Envase y embalaje compuesto de recipiente de plástico, con una caja de cartón', value: '6HG2' },
    { label: 'Envase y embalaje compuesto de recipiente de plástico, con un bidón (tambor) de plástico', value: '6HH1' },
    { label: 'Bulto de plástico', value: '7H1' },
    { label: 'Bulto de tela', value: '7L1' },
    { label: 'Bidón (tambor) de acero 1 de tapa no desmontable', value: '1A1' },
    { label: 'Bidón (tambor) de acero 1 de tapa desmontable', value: '1A2' },
    { label: 'Bidón (tambor) de aluminio de tapa no desmontable', value: '1B1' },
    { label: 'Bidón (tambor) de aluminio de tapa desmontable', value: '1B2' },
    { label: 'Bidón (tambor) de madera contrachapada', value: '1D' },
    { label: 'Bidón (tambor) de cartón', value: '1G' },
    { label: 'Bidón (tambor) de metal que no sea acero ni aluminio de tapa no desmontable', value: '1N1' },
    { label: 'Bidón (tambor) de metal que no sea acero ni aluminio de tapa desmontable', value: '1N2' },
    { label: 'Jerrican (porrón) de acero de tapa no desmontable', value: '3A1' },
    { label: 'Jerrican (porrón) de acero de tapa desmontable', value: '3A2' },
    { label: 'Jerrican (porrón) de aluminio de tapa no desmontable', value: '3B1' },
    { label: 'Jerrican (porrón) de aluminio de tapa desmontable', value: '3B2' },
    { label: 'Jerrican (porrón) de plástico de tapa no desmontable', value: '3H1' },
    { label: 'Jerrican (porrón) de plástico de tapa desmontable', value: '3H2' },
    { label: 'Caja de acero', value: '4A' },
    { label: 'Saco (bolsa) de tejido de plástico sin forro ni revestimientos interiores', value: '5H1' },
    { label: 'Saco (bolsa) de tejido de plástico a prueba de polvo (estancos a los pulverulentos)', value: '5H2' },
    { label: 'Saco (bolsa) de tejido de plástico resistente al agua', value: '5H3' },
    { label: 'Saco (bolsa) de tela sin forro ni revestimientos interiores', value: '5L1' },
    { label: 'Saco (bolsa) de tela a prueba de polvo (estancos a los pulverulentos)', value: '5L2' },
    { label: 'Envase y embalaje compuesto de recipiente de plástico, con una caja de plástico rígido', value: '6HH2' },
    { label: 'Envase y embalaje compuesto de recipiente de vidrio, porcelana o de gres, con un bidón (tambor) de acero', value: '6PA1' },
    { label: 'Envase y embalaje compuesto de recipiente de vidrio, porcelana o de gres, con una jaula o una caja de acero', value: '6PA2' },
    { label: 'Envase y embalaje compuesto de recipiente de vidrio, porcelana o de gres, con un bidón (tambor) exterior de aluminio', value: '6PB1' },
    { label: 'Envase y embalaje compuesto de recipiente de vidrio, porcelana o de gres, con una jaula o una caja de aluminio', value: '6PB2' },
    { label: 'Envase y embalaje compuesto de recipiente de vidrio, porcelana o de gres, con una caja de madera', value: '6PC' },
    { label: 'Envase y embalaje compuesto de recipiente de vidrio, porcelana o de gres, con un bidón (tambor) de madera contrachapada', value: '6PD1' },
    { label: 'Envase y embalaje compuesto de recipiente de vidrio, porcelana o de gres, con una canasta de mimbre', value: '6PD2' },
    { label: 'Envase y embalaje compuesto de recipiente de vidrio, porcelana o de gres, con un bidón (tambor) de cartón', value: '6PG1' },
    { label: 'Envase y embalaje compuesto de recipiente de vidrio, porcelana o de gres, con una caja de cartón', value: '6PG2' },
    { label: 'Envase y embalaje compuesto de recipiente de vidrio, porcelana o de gres, con un envase y embalaje de plástico expandido', value: '6PH1' },
    { label: 'Envase y embalaje compuesto de recipiente de vidrio, porcelana o de gres, con un envase y embalaje de plástico rígido', value: '6PH2' },
    { label: 'Otro', value: 'Z01' },
    { label: 'Pallet', value: 'PLT' },
];
